### ISSUE TITLE
Seg fault on 404 response

### ISSUE THREAD

**Issue by 4ybaka** [google/volley#110]
Used lib version 1.1.0rc-1, Android 6.0.1. Sending post json request. Debug log enabled but the only that I have is:

`10-14 07:26:12.310 22853-23086/com.vastuf.lotcz D/Volley: [147016] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] https://www.uctenkovka.cz/api/web/player/receipts 0x68922375 NORMAL 2> [lifetime=161], [size=19], [rc=404], [retryCount=0]
10-14 07:26:12.310 22853-23086/com.vastuf.lotcz E/Volley: [147016] BasicNetwork.performRequest: Unexpected response code 404 for https://www.uctenkovka.cz/api/web/player/receipts
10-14 07:26:12.320 22853-22853/com.vastuf.lotcz E/com.vastuf.lotcz: Can't send bill
                                                                    com.android.volley.ClientError
                                                                        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:190)
                                                                        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:113)
10-14 07:26:12.380 22853-22861/com.vastuf.lotcz A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1c in tid 22861 (JDWP)`

**Comment by jpd236** [comment]
These logs are missing the backtrace which would be essential to try and understand this. Is that not present in your logs?

There's also no clear indication that this crash is actually in the Volley code although the timing is suspicious. Certainly it would be surprising.

Please reopen with more info if you have it, ideally the following:

- Do you have the stacktrace? (Logs after the crash, generally with the DEBUG tag)
- Is this reproduceable or was this just a one-off crash?
- Does this only happen w/ Volley 1.1.0-rc1 or also older versions of Volley (i.e. Volley 1.0.0)?
- Was this on a particular device or on the emulator? Does it reproduce on other builds of Android and/or other devices?

**Comment by 4ybaka** [comment]
- Do you have the stacktrace? (Logs after the crash, generally with the DEBUG tag) - No logs after crash
- Is this reproduceable or was this just a one-off crash? - reproducible in 100%
- Does this only happen w/ Volley 1.1.0-rc1 or also older versions of Volley (i.e. Volley 1.0.0)? - on older version too
- Was this on a particular device or on the emulator? Does it reproduce on other builds of Android and/or other devices? - reproducible on emulator and device

As I understand the reason was that particular API returned non JSON response while library expects only JSON.

**Comment by jpd236** [comment]
Thank you - that is helpful context. Since this doesn't appear to be a regression I'll put it on the list to address in the next bugfix release if feasible.

If you're able to consistently reproduce this, would you be able to provide sample code so we can reproduce it ourselves and investigate a fix?

If your theory is right, it should be reproduceable without involving a network request, just by passing the raw data of the response to the parseNetworkResponse of the Request you're using (I assume a subclass of JsonRequest, right)?

All we're doing in Volley is calling new JSONArray([data]) or new JSONObject([data]), which should throw a JSONException in the event of getting invalid data, not crash in native code. That could be a platform bug, but some code to reproduce would be useful.

Would also be good to know if it is isolated to certain versions of Android (i.e. is it fixed in newer ones?)
