### ISSUE TITLE
NPE occured when setShouldCache(true);

### ISSUE THREAD

**Issue by Jamling** [google/volley#124]
Version: 1.1.0
After  Migrating from Apache HTTP, An NullPointerException occured when the `Request` `setShouldCache(true);`

Here is my sample code, MyGsonRequest extends JsonRequest.

```
    @Override
    protected void deliverResponse(IBaseResponse response) {
        this.intermediate = this.response.intermediate; // NPE occured here this.response is null.
        this.response = null;
        super.deliverResponse(response);
    }
    
    @Override
    protected Response<IBaseResponse> parseNetworkResponse(NetworkResponse response) {
        try {
            String json = new String(response.data, HttpHeaderParser.parseCharset(response.headers));
            Response<IBaseResponse> ret = Response.success(getData(json.trim(), response), parseCacheHeaders(response,
                ttl));
            this.response = ret;
            return ret;
        } catch (UnsupportedEncodingException e) {
            return Response.error(new ParseError(e));
        } catch (JsonSyntaxException e) {
            return Response.error(new ParseError(e));
        }
    }
```

This code works well in v1.0.0

**Comment by jpd236** [comment]
Thanks for the report + sample code!

At a glance, I can't see why this would have regressed from 1.0.0 to 1.1.0. CacheDispatcher is still calling Request#parseNetworkResponse prior to any calls to postResponse.

Would you be able to provide a full sample app that we can run that demonstrates the issue, rather than just an isolated snippet?

If that's too difficult, the following might be informative as well:

- The full stack trace of the crash 
- Call "adb shell setprop log.tag.Volley VERBOSE", restart your process, and then capture all of the logcat output from the request with the "Volley" tag. This is Volley's verbose logging which will help us trace the request through. It might also be necessary to comment out the crashing code as Volley only dumps the full set of request markers upon completion of a request, which won't happen if the app crashes first.

**Comment by Jamling** [comment]
Thank you for your reply, the full [GsonRequest](https://github.com/Jamling/QuickAF/blob/master/library/src/cn/ieclipse/af/volley/GsonRequest.java). 

Volley log:
```
12-09 09:14:31.856 13450-13467/? V/Volley: [339] CacheDispatcher.run: start new dispatcher
12-09 09:14:34.608 13450-13468/? D/Volley: [340] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] http://182.254.130.186:8098/lt/syjs/warnssjs.do?sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 1> [lifetime=118], [size=590], [rc=200], [retryCount=0]
12-09 09:14:34.632 13450-13450/? D/Volley: [1] MarkerLog.finish: (144  ms) [ ] http://182.254.130.186:8098/lt/syjs/warnssjs.do?sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 1
12-09 09:14:34.633 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [ 1] add-to-queue
12-09 09:14:34.633 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [340] network-queue-take
12-09 09:14:34.633 13450-13450/? D/Volley: [1] MarkerLog.finish: (+120 ) [340] network-http-complete
12-09 09:14:34.634 13450-13450/? D/Volley: [1] MarkerLog.finish: (+16  ) [340] network-parse-complete
12-09 09:14:34.634 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [340] post-response
12-09 09:14:34.634 13450-13450/? D/Volley: [1] MarkerLog.finish: (+8   ) [ 1] done
12-09 09:14:36.120 13450-13467/? D/Volley: [339] WaitingRequestManager.maybeAddToWaitingRequests: new request, sending to network http://182.254.130.186:8098/lt/sysDictVal/getSysDictValByData.do?token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android
12-09 09:14:36.215 13450-13469/? D/Volley: [341] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] http://182.254.130.186:8098/lt/sysDictVal/getSysDictValByData.do?token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 2> [lifetime=92], [size=514], [rc=200], [retryCount=0]
12-09 09:14:36.268 13450-13450/? D/Volley: [1] MarkerLog.finish: (148  ms) [ ] http://182.254.130.186:8098/lt/sysDictVal/getSysDictValByData.do?token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 2
12-09 09:14:36.268 13450-13467/? D/Volley: [339] WaitingRequestManager.maybeAddToWaitingRequests: new request, sending to network http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android
12-09 09:14:36.268 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [ 1] add-to-queue
12-09 09:14:36.268 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-queue-take
12-09 09:14:36.268 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-miss
12-09 09:14:36.269 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [341] network-queue-take
12-09 09:14:36.269 13450-13450/? D/Volley: [1] MarkerLog.finish: (+95  ) [341] network-http-complete
12-09 09:14:36.269 13450-13450/? D/Volley: [1] MarkerLog.finish: (+17  ) [341] network-parse-complete
12-09 09:14:36.269 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [341] network-cache-written
12-09 09:14:36.270 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [341] post-response
12-09 09:14:36.270 13450-13450/? D/Volley: [1] MarkerLog.finish: (+34  ) [ 1] done
12-09 09:14:36.446 13450-13470/? D/Volley: [342] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 3> [lifetime=177], [size=230], [rc=200], [retryCount=0]
12-09 09:14:36.465 13450-13450/? D/Volley: [1] MarkerLog.finish: (197  ms) [ ] http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 3
12-09 09:14:36.466 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [ 1] add-to-queue
12-09 09:14:36.466 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-queue-take
12-09 09:14:36.466 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-miss
12-09 09:14:36.466 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [342] network-queue-take
12-09 09:14:36.466 13450-13450/? D/Volley: [1] MarkerLog.finish: (+178 ) [342] network-http-complete
12-09 09:14:36.467 13450-13450/? D/Volley: [1] MarkerLog.finish: (+7   ) [342] network-parse-complete
12-09 09:14:36.467 13450-13450/? D/Volley: [1] MarkerLog.finish: (+2   ) [342] network-cache-written
12-09 09:14:36.467 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [342] post-response
12-09 09:14:36.467 13450-13450/? D/Volley: [1] MarkerLog.finish: (+9   ) [ 1] done
12-09 09:14:36.652 13450-13471/? D/Volley: [343] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] http://182.254.130.186:8098/lt/ddzZhxx/getData.do?btm=2017-12-09+08&etm=2017-12-09+09&fname=%E9%BE%99%E6%BB%A9&sfid=300A0E00_BSP&tmtype=1&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 4> [lifetime=77], [size=97], [rc=200], [retryCount=0]
12-09 09:14:36.670 13450-13450/? D/Volley: [1] MarkerLog.finish: (96   ms) [ ] http://182.254.130.186:8098/lt/ddzZhxx/getData.do?btm=2017-12-09+08&etm=2017-12-09+09&fname=%E9%BE%99%E6%BB%A9&sfid=300A0E00_BSP&tmtype=1&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 4
12-09 09:14:36.670 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [ 1] add-to-queue
12-09 09:14:36.671 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [343] network-queue-take
12-09 09:14:36.672 13450-13450/? D/Volley: [1] MarkerLog.finish: (+78  ) [343] network-http-complete
12-09 09:14:36.672 13450-13450/? D/Volley: [1] MarkerLog.finish: (+6   ) [343] network-parse-complete
12-09 09:14:36.673 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [343] post-response
12-09 09:14:36.673 13450-13450/? D/Volley: [1] MarkerLog.finish: (+12  ) [ 1] done
12-09 09:14:39.147 13450-13467/? D/Volley: [339] WaitingRequestManager.maybeAddToWaitingRequests: new request, sending to network http://182.254.130.186:8098/lt/sysDictVal/getSysDictValByData.do?token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android
12-09 09:14:39.216 13450-13467/? D/Volley: [339] WaitingRequestManager.maybeAddToWaitingRequests: new request, sending to network http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android
12-09 09:14:39.277 13450-13468/? D/Volley: [340] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] http://182.254.130.186:8098/lt/sysDictVal/getSysDictValByData.do?token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 5> [lifetime=68], [size=514], [rc=200], [retryCount=0]
12-09 09:14:39.277 13450-13469/? D/Volley: [341] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 6> [lifetime=47], [size=230], [rc=200], [retryCount=0]
12-09 09:14:39.309 13450-13450/? D/Volley: [1] MarkerLog.finish: (100  ms) [ ] http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 6
12-09 09:14:39.309 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [ 1] add-to-queue
12-09 09:14:39.309 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-queue-take
12-09 09:14:39.309 13450-13450/? D/Volley: [1] MarkerLog.finish: (+2   ) [339] cache-hit
12-09 09:14:39.309 13450-13450/? D/Volley: [1] MarkerLog.finish: (+5   ) [339] cache-hit-parsed
12-09 09:14:39.309 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-hit-refresh-needed
12-09 09:14:39.309 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [339] post-response
12-09 09:14:39.310 13450-13450/? D/Volley: [1] MarkerLog.finish: (+13  ) [ 1] intermediate-response
12-09 09:14:39.310 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [341] network-queue-take
12-09 09:14:39.310 13450-13450/? D/Volley: [1] MarkerLog.finish: (+47  ) [341] network-http-complete
12-09 09:14:39.310 13450-13450/? D/Volley: [1] MarkerLog.finish: (+2   ) [341] network-parse-complete
12-09 09:14:39.310 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [341] network-cache-written
12-09 09:14:39.310 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [341] post-response
12-09 09:14:39.311 13450-13450/? D/Volley: [1] MarkerLog.finish: (+29  ) [ 1] done
12-09 09:14:39.313 13450-13450/? D/Volley: [1] MarkerLog.finish: (174  ms) [ ] http://182.254.130.186:8098/lt/sysDictVal/getSysDictValByData.do?token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 5
12-09 09:14:39.314 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [ 1] add-to-queue
12-09 09:14:39.314 13450-13470/? D/Volley: [342] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] http://182.254.130.186:8098/lt/ddzZhxx/getData.do?btm=2017-12-09+08&etm=2017-12-09+09&fname=%E9%BE%99%E6%BB%A9&sfid=300A0E00_BSP&tmtype=1&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 7> [lifetime=44], [size=97], [rc=200], [retryCount=0]
12-09 09:14:39.314 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-queue-take
12-09 09:14:39.314 13450-13450/? D/Volley: [1] MarkerLog.finish: (+2   ) [339] cache-hit
12-09 09:14:39.314 13450-13450/? D/Volley: [1] MarkerLog.finish: (+5   ) [339] cache-hit-parsed
12-09 09:14:39.314 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-hit-refresh-needed
12-09 09:14:39.314 13450-13450/? D/Volley: [1] MarkerLog.finish: (+2   ) [339] post-response
12-09 09:14:39.315 13450-13450/? D/Volley: [1] MarkerLog.finish: (+60  ) [ 1] intermediate-response
12-09 09:14:39.315 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [340] network-queue-take
12-09 09:14:39.315 13450-13450/? D/Volley: [1] MarkerLog.finish: (+68  ) [340] network-http-complete
12-09 09:14:39.315 13450-13450/? D/Volley: [1] MarkerLog.finish: (+3   ) [340] network-parse-complete
12-09 09:14:39.315 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [340] network-cache-written
12-09 09:14:39.315 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [340] post-response
12-09 09:14:39.316 13450-13450/? D/Volley: [1] MarkerLog.finish: (+33  ) [ 1] done
12-09 09:14:39.325 13450-13450/? D/Volley: [1] MarkerLog.finish: (55   ms) [ ] http://182.254.130.186:8098/lt/ddzZhxx/getData.do?btm=2017-12-09+08&etm=2017-12-09+09&fname=%E9%BE%99%E6%BB%A9&sfid=300A0E00_BSP&tmtype=1&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 7
12-09 09:14:39.325 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [ 1] add-to-queue
12-09 09:14:39.325 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [342] network-queue-take
12-09 09:14:39.325 13450-13450/? D/Volley: [1] MarkerLog.finish: (+44  ) [342] network-http-complete
12-09 09:14:39.325 13450-13450/? D/Volley: [1] MarkerLog.finish: (+5   ) [342] network-parse-complete
12-09 09:14:39.326 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [342] post-response
12-09 09:14:39.326 13450-13450/? D/Volley: [1] MarkerLog.finish: (+6   ) [ 1] done
12-09 09:14:39.329 13450-13450/? D/Volley: [1] MarkerLog.finish: (15   ms) [ ] http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 8
12-09 09:14:39.330 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [ 1] add-to-queue
12-09 09:14:39.330 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-queue-take
12-09 09:14:39.330 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [339] cache-hit
12-09 09:14:39.330 13450-13450/? D/Volley: [1] MarkerLog.finish: (+6   ) [339] cache-hit-parsed
12-09 09:14:39.330 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] post-response
12-09 09:14:39.330 13450-13450/? D/Volley: [1] MarkerLog.finish: (+8   ) [ 1] done
12-09 09:14:41.385 13450-13467/? D/Volley: [339] WaitingRequestManager.maybeAddToWaitingRequests: new request, sending to network http://182.254.130.186:8098/lt/sysDictVal/getSysDictValByData.do?token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android
12-09 09:14:41.441 13450-13467/? D/Volley: [339] WaitingRequestManager.maybeAddToWaitingRequests: new request, sending to network http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android
12-09 09:14:41.508 13450-13471/? D/Volley: [343] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] http://182.254.130.186:8098/lt/sysDictVal/getSysDictValByData.do?token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 9> [lifetime=73], [size=514], [rc=200], [retryCount=0]
12-09 09:14:41.540 13450-13450/? D/Volley: [1] MarkerLog.finish: (162  ms) [ ] http://182.254.130.186:8098/lt/sysDictVal/getSysDictValByData.do?token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 9
12-09 09:14:41.540 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [ 1] add-to-queue
12-09 09:14:41.540 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-queue-take
12-09 09:14:41.540 13450-13450/? D/Volley: [1] MarkerLog.finish: (+2   ) [339] cache-hit
12-09 09:14:41.540 13450-13450/? D/Volley: [1] MarkerLog.finish: (+5   ) [339] cache-hit-parsed
12-09 09:14:41.541 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-hit-refresh-needed
12-09 09:14:41.541 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [339] post-response
12-09 09:14:41.541 13450-13450/? D/Volley: [1] MarkerLog.finish: (+49  ) [ 1] intermediate-response
12-09 09:14:41.541 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [343] network-queue-take
12-09 09:14:41.541 13450-13450/? D/Volley: [1] MarkerLog.finish: (+75  ) [343] network-http-complete
12-09 09:14:41.541 13450-13450/? D/Volley: [1] MarkerLog.finish: (+2   ) [343] network-parse-complete
12-09 09:14:41.542 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [343] network-cache-written
12-09 09:14:41.542 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [343] post-response
12-09 09:14:41.542 13450-13450/? D/Volley: [1] MarkerLog.finish: (+27  ) [ 1] done
12-09 09:14:41.547 13450-13467/? D/Volley: [339] WaitingRequestManager.maybeAddToWaitingRequests: Request for cacheKey=http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android is in flight, putting on hold.
12-09 09:14:41.554 13450-13469/? D/Volley: [341] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 10> [lifetime=94], [size=230], [rc=200], [retryCount=0]
12-09 09:14:41.558 13450-13469/? V/Volley: [341] WaitingRequestManager.onResponseReceived: Releasing 1 waiting requests for cacheKey=http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android.
12-09 09:14:41.575 13450-13450/? D/Volley: [1] MarkerLog.finish: (141  ms) [ ] http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 10
12-09 09:14:41.575 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [ 1] add-to-queue
12-09 09:14:41.575 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [339] cache-queue-take
12-09 09:14:41.576 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [339] cache-hit
12-09 09:14:41.576 13450-13450/? D/Volley: [1] MarkerLog.finish: (+5   ) [339] cache-hit-parsed
12-09 09:14:41.576 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-hit-refresh-needed
12-09 09:14:41.576 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [339] post-response
12-09 09:14:41.576 13450-13450/? D/Volley: [1] MarkerLog.finish: (+16  ) [ 1] intermediate-response
12-09 09:14:41.576 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [341] network-queue-take
12-09 09:14:41.577 13450-13450/? D/Volley: [1] MarkerLog.finish: (+97  ) [341] network-http-complete
12-09 09:14:41.577 13450-13450/? D/Volley: [1] MarkerLog.finish: (+2   ) [341] network-parse-complete
12-09 09:14:41.577 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [341] network-cache-written
12-09 09:14:41.577 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [341] post-response
12-09 09:14:41.577 13450-13450/? D/Volley: [1] MarkerLog.finish: (+17  ) [ 1] done
12-09 09:14:41.668 13450-13468/? D/Volley: [340] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] http://182.254.130.186:8098/lt/ddzZhxx/getData.do?btm=2017-12-09+08&etm=2017-12-09+09&fname=%E9%BE%99%E6%BB%A9&sfid=300A0E00_BSP&tmtype=1&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 11> [lifetime=163], [size=97], [rc=200], [retryCount=0]

```

carash log

```
12-09 09:14:41.582 13450-13450/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: cn.ieclipse.af.longtan, PID: 13450
                                                   java.lang.NullPointerException: Attempt to read from field 'boolean com.android.volley.Response.intermediate' on a null object reference
                                                       at cn.ieclipse.af.volley.GsonRequest.deliverResponse(GsonRequest.java:53)
                                                       at cn.ieclipse.af.volley.GsonRequest.deliverResponse(GsonRequest.java:38)
                                                       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

the full sample app need login and

**Comment by Jamling** [comment]
The sample app you can download [here](http://temp.ieclipse.cn/157250921/QuickAF1212-debug.apk), you can touch the `Refresh&Recycler` top tab under `UI samples`, then tap the second `RefreshRecyclerSample` enter the sample, try to pull to refresh until the crash occured. The sample app code is [QuickAF](https://github.com/Jamling/QuickAF), the sample app has little change from github code (change the load function argument to true so that `Request#setShouldCache` argument is true )

**Comment by Jamling** [comment]
I note that the last volley log before crash is 
```
12-09 09:14:41.575 13450-13450/? D/Volley: [1] MarkerLog.finish: (141  ms) [ ] http://182.254.130.186:8098/lt/ddzZhxx/getSfidList.do?dtype=BSP&sfid=300A0E00&token=82ea865708d34a9489bea8b1d7badc57&uid=1&clientType=Android 0x7d14ee2f NORMAL 10
12-09 09:14:41.575 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [ 1] add-to-queue
12-09 09:14:41.575 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [339] cache-queue-take
12-09 09:14:41.576 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [339] cache-hit
12-09 09:14:41.576 13450-13450/? D/Volley: [1] MarkerLog.finish: (+5   ) [339] cache-hit-parsed
12-09 09:14:41.576 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [339] cache-hit-refresh-needed
12-09 09:14:41.576 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [339] post-response
12-09 09:14:41.576 13450-13450/? D/Volley: [1] MarkerLog.finish: (+16  ) [ 1] intermediate-response
12-09 09:14:41.576 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [341] network-queue-take
12-09 09:14:41.577 13450-13450/? D/Volley: [1] MarkerLog.finish: (+97  ) [341] network-http-complete
12-09 09:14:41.577 13450-13450/? D/Volley: [1] MarkerLog.finish: (+2   ) [341] network-parse-complete
12-09 09:14:41.577 13450-13450/? D/Volley: [1] MarkerLog.finish: (+1   ) [341] network-cache-written
12-09 09:14:41.577 13450-13450/? D/Volley: [1] MarkerLog.finish: (+0   ) [341] post-response
12-09 09:14:41.577 13450-13450/? D/Volley: [1] MarkerLog.finish: (+17  ) [ 1] done
```
then 12-09 09:14:41.582 the app crashed when my request `protected void deliverResponse(IBaseResponse response) {` 

I saved the `response` when `parseNetworkResponse`, I searched the code in volley project to try to find the place where `response` set to null after  `parseNetworkResponse`, but nothing found.

**Comment by jpd236** [comment]
Thanks for all of the details! @uhager FYI

This certainly seems like a behavior change from 1.0.0 to 1.1.0. GsonRequest is making an assumption that it will always receive a call to parseNetworkResponse prior to deliverResponse. However - I don't think this was a fair assumption to make, as it relied on an implementation detail of Volley. We don't like to break these assumptions when reasonable if they impact apps, but in this case I'm leaning towards it being unreasonable to fix in Volley. 

In 1.0.0, when a Request is added to the queue while a request for the same cache key is in flight, the requests would be held back until the response for that request came back. At that point, each held-back request would be reinserted into the cache queue, where they would re-parse the same response back from the cache and then have the result dispatched. But this is not ideal - if there was a value in the cache that was usable and just stale, the other requests would still sit waiting for the network response rather than use the usable but stale cache response while waiting for the network to come back. It also meant that the same data would be re-parsed from the cache for each in-flight request.

This was [fixed](https://github.com/google/volley/commit/b2bb59ab2ff08f4d468303071f050ce938349379?diff=split) in 1.1.0. But a side effect of this fix is that when the request comes back from the network, rather than reinsert the request into the Cache queue, we just deliver the response as parsed by that first request object to the other request objects. As such, deliverResponse is called without a preceding (and unnecessary) call to parseNetworkResponse, and GsonRequest crashes because it hasn't gotten a Response object in parseNetworkResponse.

This could be "fixed" in Volley by making an unnecessary call to parseNetworkResponse in CacheDispatcher.WaitingRequestManager#onResponseReceived prior to calling postResponse. If there are other reports of similar issues along those lines, we could consider it. But for one app, I don't think making every other app pay the extra cost of the unnecessary response parsing is worthwhile, unfortunately.

I would suggest updating your code not to rely on this assumption. It looks like the main thing this section of code is aiming to do is bubble up the "intermediate" bit from Response to a higher-level class. If that's critical, the main option I can think of would be to provide your own implementation of ResponseDelivery which can propagate this bit to Requests as needed. FWIW, as far as I can tell nothing in the sample app actually makes use of this bit except for logging anyway.

Will keep an eye on further reports of issues related to this to see if we should reconsider.

**Comment by Jamling** [comment]
Thank your for your info about [fjix](https://github.com/google/volley/commit/b2bb59ab2ff08f4d468303071f050ce938349379?diff=split), I known that the root cause of crash in my app.

I am not plan to implement `ResponseDelivery`, I just want to known the response delivered to Response.Listener is `intermediate` or not, is there any other simple solution?

**Comment by uhager** [comment]
Since we only have intermediate responses for soft TTL cache hits (entry from cache is delivered, refresh in background), and for those we still call parseNetworkResponse for every request, wouldn't a null-check on response solve this? If there is no response, then there was no cache entry (or it was expired).

I'm not sure though if holding on to the response is the best way to do this. Maybe override request.setCacheEntry(entry), and set 
boolean isIntermediate = !entry.isExpired() && entry.refreshNeeded(). 
Though there could be some edge-cases where the entry expires just the millisecond this is called.

Alternatively, you could use NetworkResponse.networkTimeMs and store that in the request. This is 0 for NetworkResponses created from cache entries, and >0 for NetworkResponses from the network. So initialize to -1L, store it in the request during parseNetworkResponse, and then check it in deliverResponse together with whether or not the request has a cache entry (it will have one if the cache entry from disk was on soft TTL or expired, but not if the entry was fresh).
boolean isIntermediate = getCacheEntry() != null && requestNetworkTimeMs == 0 
This is probably the cleanest, and you don't need to keep the whole response, just the networkTimeMs.

**Comment by Jamling** [comment]
@uhager Thank you for your tip. As @jpd236 's explain, it's not a good idea to handle resonse in `deliverResponse`.  The cache rule should be controled by the server side. I will drop client cache control, but I think it should to tell the Response.Listener whether the response data is intermediate or not

**Comment by jpd236** [comment]
It's not an unreasonable request. Unfortunately deliverResponse is abstract and public API and thus can't be changed directly without a major version change (which we have no plan to do at this time).

However, we might be able to add a deliverResponse(T response, boolean isIntermediate) or similar method whose default implementation delegates to deliverResponse(T response), and use that within our own ExecutorResponseDelivery implementation.
