### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by wxz-Android** [google/volley#130]
[798] NetworkDispatcher.run: Unhandled exception java.util.ConcurrentModificationException
                                                                 java.util.ConcurrentModificationException
                                                                     at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
                                                                     at java.util.HashMap$EntryIterator.next(HashMap.java:1475)
                                                                     at java.util.HashMap$EntryIterator.next(HashMap.java:1475)
                                                                     at java.util.HashMap.putMapEntries(HashMap.java:511)
                                                                     at java.util.HashMap.putAll(HashMap.java:784)
                                                                     at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:93)
                                                                     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:97)
                                                                     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)

`  HashMap<String, String> map = new HashMap<String, String>();
        map.putAll(request.getHeaders());
        map.putAll(additionalHeaders);
`

**Comment by megataps** [comment]
I got the same exception when load image

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
       at java.util.HashMap$ValueIterator.next(HashMap.java:838)
       at com.android.volley.toolbox.ImageLoader$4.run(SourceFile:464)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5341)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by joebowbeer** [comment]
@wxz-Android Which version of volley? `HurlStack.performRequest` does not exist in 1.1.0

**Comment by joebowbeer** [comment]
@megataps I suspect `ImageLoader.ImageContainer.cancelRequest` was called while `BatchedImageRequest.batchResponse` was iterating over the `mBatchedResponses` values.

**Comment by jpd236** [comment]
@wxz-Android The additionalHeaders map passed into performRequest (now executeRequest in Volley 1.1.0, but otherwise functionally the same for the sake of this bug) must not be modified after that point. It appears something else in your code has mutated it while HurlStack is trying to read it. There is no way for Volley to safely iterate over the provided map if it is being mutated at the same time.

@megataps Different issue, and it looks likely to be what @joebowbeer pointed out. cancelRequest isn't safe to call off the main thread. I'll file a separate bug to either improve the documentation or relax this restriction.
