### ISSUE TITLE
StrictMode exception,http connection should be closed when no use . HurlStack.java 

### ISSUE THREAD

**Issue by businezcc** [google/volley#138]
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               java.lang.Throwable: Explicit termination method 'close' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                   at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:103)
                                                                   at java.net.Socket.createImpl(Socket.java:464)
                                                                   at java.net.Socket.getImpl(Socket.java:530)
                                                                   at java.net.Socket.setSoSndTimeout(Socket.java:1194)
                                                                   at com.android.okhttp.Connection.setTimeouts(Connection.java:508)
                                                                   at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:400)
                                                                   at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
                                                                   at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:356)
                                                                   at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:273)
                                                                   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:474)
                                                                   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:422)
                                                                   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
                                                                   at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
                                                                   at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
                                                                   at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:110)
                                                                   at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:97)
                                                                   at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)

**Comment by jpd236** [comment]
Looks like we never call HttpUrlConnection#disconnect. Seems like we should per the Javadoc.

At a glance it seems like the easiest way would be to:

- Call disconnect directly in HurlStack#executeRequest if the response has no body
- Wrap the InputStream returned by HurlStack#inputStreamFromConnection to call disconnect() from InputStream#close, so the connection is closed once the Network has consumed the stream contents. BasicNetwork#inputStreamToBytes does close the InputStream already AFAICT.

**Comment by Yaun1234** [comment]
HttpUrlConnection#disconnect should also be called if `connection.getResponseCode()` throws an exception, e.g. a SocketTimeoutException.

**Comment by jpd236** [comment]
For whatever reason I wasn't able to reproduce this strict mode violation, but I've prepared a fix that should be safe nonetheless in #176. Would appreciate if someone here could either validate the fix or provide more info on how to reproduce this (sample app and/or details of the platform that is being used).
