### ISSUE TITLE
Volley Exception

### ISSUE THREAD

**Issue by Jparrgam** [google/volley#148]
**the library has one exception the following**, why this exception ?

`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 1887003011 byte allocation with 8388608 free bytes and 190MB until OOM
       at com.android.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:323)
       at com.android.volley.toolbox.DiskBasedCache.readString(DiskBasedCache.java:541)
       at com.android.volley.toolbox.DiskBasedCache.readStringStringMap(DiskBasedCache.java:564)
       at com.android.volley.toolbox.DiskBasedCache$CacheHeader.readHeader(DiskBasedCache.java:404)
       at com.android.volley.toolbox.DiskBasedCache.initialize(DiskBasedCache.java:157)
       at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:84)`

**Comment by joebowbeer** [comment]
This was fixed and the fix is available in a snapshot.

See #12 and #127

**Comment by jpd236** [comment]
Thanks @joebowbeer. @Jparrgam, please let us know if you are still seeing issues on that snapshot.
