### ISSUE TITLE
E/Volley: [2040] NetworkDispatcher.run: Unhandled exception java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference 

### ISSUE THREAD

**Issue by farislivemaker** [google/volley#150]
Am using volley for my application, Initially my application was designed to use Asyn task for network call, after that modified to volley. Previous version was in play store. Now i changed all network call to volley in the same application and updated in play store. 

If the application is install for the first time from play store after the updated(Volley version) is working fine.

Problem comes when existing user updated the app from play(Volley version) to their existing Asyn task version.

The POST request for the first time is not working the below error is thrown BUT from the second time its working.

Am unable to solve this issue please help. I have already gone through [this](https://github.com/google/volley/issues/95) issue. can't able to solve

`E/Volley: [2040] NetworkDispatcher.run: Unhandled exception java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                         java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                             at libcore.net.UriCodec.encode(UriCodec.java:132)
                                             at java.net.URLEncoder.encode(URLEncoder.java:57)
                                             at com.android.volley.Request.encodeParameters(Request.java:450)
                                             at com.android.volley.Request.getBody(Request.java:436)
                                             at com.android.volley.toolbox.HurlStack.addBodyIfExists(HurlStack.java:260)
                                             at com.android.volley.toolbox.HurlStack.setConnectionParametersForRequest(HurlStack.java:234)
                                             at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:107)
                                             at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
                                             at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)`

**Comment by jpd236** [comment]
From the stack trace it appears you've overridden Request#getParams() or Request#getPostParams() to return a map, and have inserted an entry with either a null key or value. Keys/values of the map returned by these methods must be non-null.

If this is not the case, please provide more information, like the version of Volley you are using (it looks like it might be 1.0.0 from the lines of code which is not the latest version) and ideally a small sample project reproducing the issue, or at a minimum your Request subclass's source code.

**Comment by farislivemaker** [comment]
Yeah, Thank you @jpd236 i got a null value in  Request#getPostParams() solved this issue thanks for commenting it out.
