### ISSUE TITLE
Exception: java.util.ConcurrentModificationException on 1.1.1-rc1

### ISSUE THREAD

**Issue by megataps** [google/volley#205]
I got this crash report on the latest build 1.1.1-rc1

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at com.android.volley.toolbox.ImageLoader$4.run(SourceFile:491)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5318)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)

**Comment by hero0812** [comment]
do not modify the ArrayList when it is being traversed

**Comment by jpd236** [comment]
Assuming the line in question is indeed line 491 of ImageLoader.java:

```java
for (ImageContainer container : bir.mContainers) {
```

then the issue would be something mutating mContainers during this iteration. 

This line of code always runs on the main thread (it is posted to a main thread handler). There are four other methods which mutate mContainers, but as far as I can tell, all of these are only called by methods which first invoke Threads.throwIfNotOnMainThread(), and so would throw a different failure if they were being called here on a different thread.

There are thus only two possibilities I can think of:

- Something inside this loop is causing the list to be mutated. The ImageListeners created by Volley don't appear to ever do this. Are you using a custom ImageListener, and if so, does that ImageListener ever call ImageContainer#cancelRequest or ImageLoader#get?
-This isn't actually the line of code that's crashing. (Proguard appears to be involved, since it says "SourceFile" rather than the actual file).

I don't think this is a regression from older builds. Sounds like this was a one-off crash reported in the wild? Do you have more information (and ideally code) showing how you are using ImageLoader?

**Comment by jpd236** [comment]
https://stackoverflow.com/questions/35479128/volley-image-loader-concurrentmodificationexception seems to be a similar crash with sample code in the wild.

**Comment by javad-vovin** [comment]
We have a similar exception.
It's very hard to produce, but the scenario is ImageContainer cancel request but handler in batchResponse is still processing mBatchedResponses, when this happen java.util.ConcurrentModificationException will occurred.

**Comment by joebowbeer** [comment]
CME is most often thrown from a single thread, despite the name, so that seems most likely the case here.

These iterators are both in flight when a listener may be called on the same thread:
```
for (BatchedImageRequest bir : mBatchedResponses.values()) {
    for (ImageContainer container : bir.mContainers) {
```

The problem can probably be avoided by switching to indexed loops:

```
for (int i = 0; i < bir.mContainers.size(); i++) {
    ImageContainer container = bir.mContainers.get(i);
```
