### ISSUE TITLE
Error raised 'ProtocolException: Unexpected status line' after Media Player API(MediaHTTPService)

### ISSUE THREAD

**Issue by imknown** [google/volley#208]
Hi~
The player is [JiaoZiVideoPlayer](https://github.com/lipangit/JiaoZiVideoPlayer).
Play the media url and close/release the player, and make a http call via `Volley` (1.1.1).
Then this issue can be reproducted.
And I notice that it appears on `Android 8` and **DOES NOT** appear on `Android 6`

----

Stacktrace is here:

```
197  I/JZResizeTextureView: onMeasure  [153293809] 
242  I/chatty: uid=10083() identical 2 lines
243  I/JZResizeTextureView: onMeasure  [153293809] 
368  I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [168369446] 

469  W/MediaPlayer: Use of stream types is deprecated for operations other than volume control
470  W/MediaPlayer: See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
486  W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder

539  W/om.qmzhhchsh.y: Accessing hidden method Landroid/media/MediaPlayer;->setDataSource(Ljava/lang/String;Ljava/util/Map;)V (light greylist, reflection)

559  V/MediaHTTPService: MediaHTTPService(android.media.MediaHTTPService@34ea14f): Cookies: null
635  W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
637  V/MediaHTTPService: makeHTTPConnection: CookieManager created: java.net.CookieManager@e23c5e5
641  V/MediaHTTPService: makeHTTPConnection(android.media.MediaHTTPService@34ea14f): cookieHandler: java.net.CookieManager@e23c5e5 Cookies: null

963  I/JiaoZiVideoPlayer: onVideoSizeChanged  [168369446] 
037  I/JZResizeTextureView: onMeasure  [153293809] 
057  I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1440]
059  I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1260]
061  I/JZResizeTextureView: onMeasure  [153293809] 
061  I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1440]
061  I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1260]
062  I/JZResizeTextureView: onMeasure  [153293809] 
062  I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1440]
062  I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1260]
062  I/JZResizeTextureView: onMeasure  [153293809] 
062  I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1440]
062  I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1260]
895  D/JiaoZiVideoPlayer: releaseAllVideos
912  I/JiaoZiVideoPlayer: onCompletion  [168369446] 
912  I/JiaoZiVideoPlayer: onStateNormal  [168369446] 
245  V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
245  V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null

617  D/Volley: [2] RequestQueueManager.addToRequestQueue: Adding request to queue: https://api-test.test-host.com/cgb_app/usercenter/mycnt/v1.4.0
738  D/Volley: [632] WaitingRequestManager.maybeAddToWaitingRequests: new request, sending to network 1-https://api-test.test-host.com/cgb_app/usercenter/mycnt/v1.4.0
093  D/Volley: [632] WaitingRequestManager.maybeAddToWaitingRequests: new request, sending to network https://file-test.test-host.com/img/head/2017/1226/73e774a2-f550-4c9c-8c79-9c4e3e3a78e0.jpg
389  D/Volley: [634] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] https://file-test.test-host.com/img/head/2017/1226/73e774a2-f550-4c9c-8c79-9c4e3e3a78e0.jpg 0xde229c41 LOW 13> [lifetime=279], [size=162], [rc=404], [retryCount=0]
392  E/Volley: [634] BasicNetwork.performRequest: Unexpected response code 404 for https://file-test.test-host.com/img/head/2017/1226/73e774a2-f550-4c9c-8c79-9c4e3e3a78e0.jpg
399  D/Volley: [2] MarkerLog.finish: (313  ms) [ ] https://file-test.test-host.com/img/head/2017/1226/73e774a2-f550-4c9c-8c79-9c4e3e3a78e0.jpg 0xde229c41 LOW 13
399  D/Volley: [2] MarkerLog.finish: (+0   ) [ 2] add-to-queue
399  D/Volley: [2] MarkerLog.finish: (+1   ) [632] cache-queue-take
399  D/Volley: [2] MarkerLog.finish: (+0   ) [632] cache-miss
399  D/Volley: [2] MarkerLog.finish: (+9   ) [634] network-queue-take
399  D/Volley: [2] MarkerLog.finish: (+300 ) [634] post-error
399  D/Volley: [2] MarkerLog.finish: (+3   ) [ 2] done

373  W/System.err: com.android.volley.NoConnectionError: java.net.ProtocolException: Unexpected status line: D�Dθ�:��]�$�
373  W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:181)
373  W/System.err:     at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
373  W/System.err:     at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
373  W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
374  W/System.err: Caused by: java.net.ProtocolException: Unexpected status line: D�Dθ�:��]�$�
374  W/System.err:     at com.android.okhttp.internal.http.StatusLine.parse(StatusLine.java:54)
374  W/System.err:     at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
374  W/System.err:     at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
374  W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
374  W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
375  W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
375  W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
375  W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
375  W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
375  W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
375  W/System.err:     at com.android.volley.toolbox.HurlStack.executeRequest(HurlStack.java:96)
375  W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:123)
375  W/System.err: 	... 3 more

387  D/Volley: [2] MarkerLog.finish: (2760 ms) [ ] https://api-test.test-host.com/cgb_app/usercenter/mycnt/v1.4.0 0xf9d2c5e3 NORMAL 12
387  D/Volley: [2] MarkerLog.finish: (+0   ) [ 2] add-to-queue
387  D/Volley: [2] MarkerLog.finish: (+5   ) [632] cache-queue-take
387  D/Volley: [2] MarkerLog.finish: (+105 ) [632] cache-hit-expired
387  D/Volley: [2] MarkerLog.finish: (+22  ) [635] network-queue-take
387  D/Volley: [2] MarkerLog.finish: (+2412) [635] post-error
387  D/Volley: [2] MarkerLog.finish: (+216 ) [ 2] done
784  D/Volley: [2] RequestQueueManager.addToRequestQueue: Adding request to queue: https://api-test.test-host.com/cgb_app/message/getGropMessage/v1.4.0
```

**Comment by jpd236** [comment]
There is insufficient information here for us to look into this. The error would indicate that the server is returning unexpected data. I tried making a simple request to https://api-test.test-host.com/cgb_app/usercenter/mycnt/v1.4.0 but the SSL certificate is invalid; if I ignore that, it returns a redirect to http://test-host.com/index.php/cgb_app/usercenter/mycnt/v1.4.0, which returns a 404. But I do not see any issues.

If you can produce a sample app (ideally with code) that reproduces this issue, then we could take a closer look. Are you testing on an emulator or a specific device?

**Comment by imknown** [comment]
Hi, sorry for my late reply.  :(
And sorry again for thar the urls above are not the real addresses. I replaced them...
I rewrote a demo that reproduced this issue.

----

[VolleyAndVedioPlayer.zip](https://github.com/google/volley/files/2222211/VolleyAndVedioPlayer.zip)

----

Steps here:
1. Click `First: Play Video`;
2. Finish the video Activity quickly;
3. Click `Second: Send Http Request`;
4. If you are lucky, and you will reproduce the error.
5. If not, please try more times. :p

**Comment by jpd236** [comment]
Thanks!

I was able to reproduce this. However, it also occurs when using HttpUrlConnection directly, without Volley involved at all. This means that this is not a Volley bug, but is either an issue with the server returning invalid data or an issue with the Android platform's HttpUrlConnection class. The fact that it only happens after starting some streaming video might suggest that data from the video connection is somehow leaking into the other connection on the client side, but I'm just speculating.

I've attached a tweaked version of your app which reproduces the same bug without using Volley at all. (Actually, when the bad data comes in, it crashes rather than just logging it, but the root cause is the same). My suggestion would be to report this to the public Android bug tracker to see why it is happening. If there's a workaround that is generally applicable, we might be able to patch Volley to apply that workaround by default, so please do let me know here if/when you do report the issue so we can follow along. Otherwise, you can try using a different HttpStack implementation to avoid relying on the platform's HttpUrlConnection.

[NoVolleyVideoPlayer.zip](https://github.com/google/volley/files/2229868/NoVolleyVideoPlayer.zip)

**Comment by imknown** [comment]
:D Thx a lot~

**Comment by imknown** [comment]
Hi, @jpd236, and maybe late. :(
The AOSP framework issue reported here:
https://issuetracker.google.com/issues/113756447
