### ISSUE TITLE
Android Volley Execution throw an Exception: Unparseable date

### ISSUE THREAD

**Issue by Ankit-Kr-Verma** [google/volley#223]
E/Volley: [35258] HttpHeaderParser.parseDateAsEpoch: Unable to parse dateStr: -1, falling back to 0
    java.text.ParseException: Unparseable date: "-1" (at offset 0)
        at java.text.DateFormat.parse(DateFormat.java:579)
        at com.android.volley.toolbox.HttpHeaderParser.parseDateAsEpoch(HttpHeaderParser.java:142)
        at com.android.volley.toolbox.HttpHeaderParser.parseCacheHeaders(HttpHeaderParser.java:100)
        at com.goeventz.volley.VolleyRequest$3.parseNetworkResponse(VolleyRequest.java:121)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:87)

**Comment by jpd236** [comment]
That's not a thrown exception; it's a logged warning. The server's response includes either a "Date: -1" or "Expires: -1" header. Those are considered invalid date formats, and thus Volley treats it as a "0" per the RFC.

**Comment by Ankit-Kr-Verma** [comment]
Thanks for the quick reply.

**Comment by NickIvantsov** [comment]
Please tell me how to disable or handle this exception?
