### ISSUE TITLE
Date format issue. Kindly Help me to solve this.

### ISSUE THREAD

**Issue by snehangshubiswas** [google/volley#272]
05-15 16:57:05.365 4253-4253/? W/System: ClassLoader referenced unknown path: /data/app/com.quiz.time-1/lib/arm
05-15 16:57:06.328 4253-4253/com.quiz.time W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
05-15 16:57:06.532 4253-4282/com.quiz.time W/System: ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000009f/n/armeabi-v7a
    ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000009f/n/armeabi
05-15 16:57:06.642 4253-4253/com.quiz.time W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
05-15 16:57:07.002 4253-4261/com.quiz.time W/MediaPlayer-JNI: MediaPlayer finalized without being released
05-15 16:57:08.076 4253-4294/com.quiz.time W/Ads: Update ad debug logging enablement as false
05-15 16:57:08.186 4253-4264/com.quiz.time W/art: Suspending all threads took: 8.331ms
05-15 16:57:08.188 4253-4308/com.quiz.time W/chromium: [0515/165708.162418:WARNING:library_prefetcher.cc(328)] Code not ordered, madvise optimization skipped
05-15 16:57:10.106 4253-4264/com.quiz.time W/art: Suspending all threads took: 157.287ms
05-15 16:57:27.340 4253-4253/com.quiz.time E/RecyclerView: No adapter attached; skipping layout
05-15 16:57:29.585 4253-4315/com.quiz.time E/Volley: [3367] HttpHeaderParser.parseDateAsEpoch: Unable to parse dateStr: 0, falling back to 0
    java.text.ParseException: Unparseable date: "0" (at offset 0)
        at java.text.DateFormat.parse(DateFormat.java:579)
        at com.android.volley.toolbox.HttpHeaderParser.parseDateAsEpoch(HttpHeaderParser.java:142)
        at com.android.volley.toolbox.HttpHeaderParser.parseCacheHeaders(HttpHeaderParser.java:100)
        at com.android.volley.toolbox.StringRequest.parseNetworkResponse(StringRequest.java:90)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:87)
05-15 16:57:30.157 4253-4253/com.quiz.time E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.quiz.time, PID: 4253
    android.view.InflateException: Binary XML file line #45: Binary XML file line #45: Error inflating class com.cricket.quiz.helper.CircleImageView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.quiz.time.fragment.FragmentCategory$CategoryAdapter.onCreateViewHolder(FragmentCategory.java:221)
        at com.quiz.time.fragment.FragmentCategory$CategoryAdapter.onCreateViewHolder(FragmentCategory.java:209)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:16645)
        at android.view.ViewGroup.layout(ViewGroup.java:5471)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
        at android.view.View.layout(View.java:16645)
        at android.view.ViewGroup.layout(ViewGroup.java:5471)
        at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1191)
        at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:876)
        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:895)
        at android.view.View.layout(View.java:16645)
        at android.view.ViewGroup.layout(ViewGroup.java:5471)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16645)
        at android.view.ViewGroup.layout(ViewGroup.java:5471)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
        at android.view.View.layout(View.java:16645)
        at android.view.ViewGroup.layout(ViewGroup.java:5471)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16645)
        at android.view.ViewGroup.layout(ViewGroup.java:5471)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16645)
        at android.view.ViewGroup.layout(ViewGroup.java:5471)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16645)
        at android.view.ViewGroup.layout(ViewGroup.java:5471)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16645)
        at android.view.ViewGroup.layout(ViewGroup.java:5471)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2694)
        at android.view.View.layout(View.java:16645)
        at android.view.ViewGroup.layout(ViewGroup.java:5471)
    	at android.view.ViewRootImpl.performLayout(ViewRootImpl.ja
05-15 16:57:36.890 4253-4261/com.quiz.time W/MediaPlayer-JNI: MediaPlayer finalized without being released

**Comment by jpd236** [comment]
Volley's log is not a crash. It's just a warning. Some server you're talking to is responding with a "Date", "Expires", or "Last-Modified" header with the value "0", which is not valid according to the HTTP spec. But we just treat it like a 0 timestamp anyway and move on.

https://github.com/google/volley/blob/d1a3d5388c79ff1a6fdb904daeff9b39d0bb7d26/src/main/java/com/android/volley/toolbox/HttpHeaderParser.java#L138
