### ISSUE TITLE
Android Q 无法进行网络请求

### ISSUE THREAD

**Issue by GlimmerYang** [google/volley#293]
java.lang.RuntimeException: Stub!
    java.lang.RuntimeException: Stub!
        at org.apache.http.ProtocolVersion.<init>(ProtocolVersion.java:37)
        at ***.network.OkHttpStack.parseProtocol(OkHttpStack.java:180)
        at ***.network.OkHttpStack.performRequest(OkHttpStack.java:84)
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)

**Comment by jpd236** [comment]
Please see https://github.com/google/volley/wiki/Migrating-from-Apache-HTTP for instructions on how to migrate custom HttpStacks (like the OkHttpStack from your stack trace must be, since that's not part of Volley itself) away from depending on Apache HTTP. That is the recommended way to resolve this issue as your app will no longer need to depend on Apache HTTP.

If you still want to use Apache for some reason then you will have to manually depend on the library, which I think is documented here: https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p
