### ISSUE TITLE
Volley Unable to Parse a particular GIF

### ISSUE THREAD

**Issue by stonecauldron** [google/volley#364]
Hello,

In our codebase, we are trying to load a gif image with Volley but we've run into some problems, namely Volley throws an exception when parsing the image. This doesn't happen with other gif files, only the one we joined to this issue.

Here is the code making use of Volley (running on API 30):
```
Glide.with(ResultsActivity.this).load(thumbnailUrl)
  .thumbnail(0.5f)
  .crossFade()
  .diskCacheStrategy(DiskCacheStrategy.ALL)
  .into(holder.thumbnail);
```

And below you will find the stack trace:
```
java.lang.IllegalArgumentException: Bad position 2949201/2949120
        at java.nio.Buffer.position(Buffer.java:259)
        at java.nio.ByteBuffer.position(ByteBuffer.java:812)
        at com.bumptech.glide.gifdecoder.GifHeaderParser.skip(GifHeaderParser.java:319)
        at com.bumptech.glide.gifdecoder.GifHeaderParser.skipImageData(GifHeaderParser.java:309)
        at com.bumptech.glide.gifdecoder.GifHeaderParser.readBitmap(GifHeaderParser.java:202)
        at com.bumptech.glide.gifdecoder.GifHeaderParser.readContents(GifHeaderParser.java:93)
        at com.bumptech.glide.gifdecoder.GifHeaderParser.parseHeader(GifHeaderParser.java:67)
        at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:69)
        at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:61)
        at com.bumptech.glide.load.resource.gif.GifResourceDecoder.decode(GifResourceDecoder.java:26)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeGifWrapper(GifBitmapWrapperResourceDecoder.java:101)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:87)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperStreamResourceDecoder.decode(GifBitmapWrapperStreamResourceDecoder.java:24)
        at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperStreamResourceDecoder.decode(GifBitmapWrapperStreamResourceDecoder.java:14)
        at com.bumptech.glide.load.resource.file.FileToStreamDecoder.decode(FileToStreamDecoder.java:39)
        at com.bumptech.glide.load.resource.file.FileToStreamDecoder.decode(FileToStreamDecoder.java:17)
        at com.bumptech.glide.load.engine.DecodeJob.loadFromCache(DecodeJob.java:222)
        at com.bumptech.glide.load.engine.DecodeJob.cacheAndDecodeSourceData(DecodeJob.java:207)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:187)
        at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
        at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
        at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
        at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
        at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
        at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
```

The gif can be found here:
![anim0000-0089](https://user-images.githubusercontent.com/2352056/91191428-114f3100-e6f5-11ea-941c-2dbf0a8ea217.gif)
It was generated with [gifski](https://gif.ski)

Any ideas or pointers about what could be wrong?
Thanks

**Comment by jpd236** [comment]
I don't see what this has to do with Volley. The stack trace and code are all from [Glide](https://github.com/bumptech/glide). Would recommend you report your issue there, but feel free to reopen this if you can point more clearly to how Volley is related to this issue.

**Comment by stonecauldron** [comment]
Sorry, you're entirely right; it was an embarrassing brain fart
