### ISSUE TITLE
Differing Results in Response Parsing from AMD Windows/MacBook Pro

### ISSUE THREAD

**Issue by ChrisHelmsC** [google/volley#365]
When running an android emulator (Pixel 2, API 29) on my MacBook Pro I am able to parse my server's JSON reposes correctly. Volley is 1.1.1 for both. However, when running on my Windows machine with an AMD processor on the same emulator/API level, Volley sometimes does not get the final character of a response string. An example is below:

```
2020-08-27 13:56:59.686 12699-12699/com.example.mints D/ConnectionManager - sendLoginRequest: {"id":980,"tag":"eleonore.osinski50","name":"Mrs. Kiarra Mosciski","api_token":"SauwDXDlAF6cQ2J9wwlIcz57R3ORgtl0VnALfSRc6ocj2WL5dksVUEP2RUzL","avatar_path":"NO_AVATAR"
2020-08-27 13:56:59.703 12699-12699/com.example.mints D/AndroidRuntime: Shutting down VM
2020-08-27 13:56:59.704 12699-12699/com.example.mints E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mints, PID: 12699
    com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 168 path $.avatar_path
        at com.google.gson.Gson.fromJson(Gson.java:937)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at com.mints.fragments.login.LoginFragment$9.listen(LoginFragment.java:475)
        at com.mints.services.UserLoginService$1.onResponse(UserLoginService.java:43)
        at com.mints.services.UserLoginService$1.onResponse(UserLoginService.java:33)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.io.EOFException: End of input at line 1 column 168 path $.avatar_path
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:482)
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892) 
        at com.google.gson.Gson.fromJson(Gson.java:841) 
        at com.google.gson.Gson.fromJson(Gson.java:813) 
        at com.mints.fragments.login.LoginFragment$9.listen(LoginFragment.java:475) 
        at com.mints.services.UserLoginService$1.onResponse(UserLoginService.java:43) 
        at com.mints.services.UserLoginService$1.onResponse(UserLoginService.java:33) 
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82) 
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29) 
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

Note that the final "}" is missing in the first line. This behavior is completely random. meaning it potentially happens for every API endpoint I call, and its never guaranteed to happen. I have verified multiple times that the server is correctly sending the response, and that the same app works totally fine on my other machine and physical device (Samsung S6 edge).  I have verified that the string has this issue within the onResponse function in the StringRequest.java class.

This issue is not specific to JSON type responses, I have also seen it happen with basic text strings.
`"2020-08-27 14:55:36.995 3428-3428/com.example.**** D/TosActivationService - checkTosAccepted: Response was TOS_ACCEPTE"`
This example should show "TOS_ACCEPTED" as the response.

**Comment by jpd236** [comment]
That's very bizarre!

What HttpStack are you using? If it's the default (HurlStack), could you see if the problem is reproducible when using HttpUrlConnection directly?

Volley is ultimately just a thin wrapper around an HTTP stack, like HttpUrlConnection. I'd be surprised if the issue you were seeing was in Volley itself rather than the underlying HTTP stack. You could also try a different HTTP stack - HttpClientStack (which is deprecated, but should still be functional if you [opt into including the Apache HTTP library](https://developer.android.com/about/versions/marshmallow/android-6.0-changes#behavior-apache-http-client)) or one of the OkHttp/Cronet-based implementations floating around to see if they have the same problem.

**Comment by ChrisHelmsC** [comment]
I can get the same error using HttpUrlConnection directly. Not sure what to do at this point. I ran it about 100 times with curl and never saw the issue.

![image](https://user-images.githubusercontent.com/10986310/91495865-3a082f80-e889-11ea-9ef8-5a9b4102874d.png)

**Comment by jpd236** [comment]
That confirms it's not specific to Volley then, unfortunately. Since you only seem to be seeing it on a Windows emulator, perhaps it is a windows-specific emulator bug.

Since you can reproduce the bug using only HTTP code from the Android platform itself, and since it appears to be specific to the emulator on one platform, my recommendation would be to try reporting the issue as an emulator issue: https://developer.android.com/studio/report-bugs#emulator-bugs.

If it turns out there's a workaround that can be done to make HttpUrlConnection behave correctly for some impacted set of devices/emulators, I'd be open to employing that workaround in Volley, though it's unclear if such a workaround would exist.

In the mean time, if you'd like to use Volley, and functionality on this particular emulator is important, then I would suggest substituting in another HTTP stack. But having never heard of an issue like this before, and since I can't find any other evidence of someone else ever seeing something like this from a quick search (though I may just not be able to find it), it doesn't seem likely that this is particularly widespread.
