### ISSUE TITLE
Volley unable to parse dateStr

### ISSUE THREAD

**Issue by alexfu2011** [google/volley#436]
E/Volley: [631] HttpHeaderParser.parseDateAsEpoch: Unable to parse dateStr: Thu, 10 Feb 2022 12:05:37 Asia/Shanghai, falling back to 0
    java.text.ParseException: Unparseable date: "Thu, 10 Feb 2022 12:05:37 Asia/Shanghai"
        at java.text.DateFormat.parse(DateFormat.java:362)
        at com.android.volley.toolbox.HttpHeaderParser.parseDateAsEpoch(HttpHeaderParser.java:135)
        at com.android.volley.toolbox.HttpHeaderParser.parseCacheHeaders(HttpHeaderParser.java:102)
        at com.android.volley.toolbox.StringRequest.parseNetworkResponse(StringRequest.java:98)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:143)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

**Comment by jpd236** [comment]
This is a non-fatal error logged when the server returns an invalid Date/Expires/Last-Modified header. As best as I can tell, [RFC1123](https://www.rfc-editor.org/rfc/rfc1123#page-55) states that it uses [RFC822](https://www.rfc-editor.org/rfc/rfc822#section-5) (with minor tweaks), which does not permit "Asia/Shanghai" to be used as a timezone.

In this case, Volley logs a warning, but assumes the dates are all "0", which means the responses won't be cached at all, but otherwise wouldn't impact your application. The server should be fixed to follow HTTP specifications. That said, I'm open to a general workaround which makes Volley's parser more flexible around timezones if there's evidence that this is a common problem.
