### ISSUE TITLE
Getting E/Volley: [19618] NetworkDispatcher.processRequest: Unhandled exception

### ISSUE THREAD

**Issue by manumathew17** [google/volley#448]
Getting error 
```
E/Volley: [19618] NetworkDispatcher.processRequest: Unhandled exception com.android.tools.idea.kotlin.UninitializedPropertyAccessException: lateinit property interceptedResponse has not been initialized
    com.android.tools.idea.kotlin.UninitializedPropertyAccessException: lateinit property interceptedResponse has not been initialized
        at com.android.tools.appinspection.network.httpurl.TrackedHttpURLConnection.getHeaderFields(TrackedHttpURLConnection.kt:336)
        at com.android.tools.appinspection.network.httpurl.HttpsURLConnectionWrapper.getHeaderFields(HttpsURLConnectionWrapper.kt:189)
        at com.android.volley.toolbox.HurlStack.executeRequest(HurlStack.java:107)
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:104)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
E/ERROR: com.android.volley.VolleyError: com.android.tools.idea.kotlin.UninitializedPropertyAccessException: lateinit property interceptedResponse has not been initialized
```

The api is working fine in postman

**Comment by manumathew17** [comment]
Thanks, @jpd236 for the update
Is it because of debug apk? because I tried in the real device also

**Comment by jpd236** [comment]
I'm not familiar enough with how Android Studio injects this logic into the APK, but I assume that if you build a production APK, or a debug APK using Gradle directly rather than from within Android Studio, either should work. I don't know that it would have anything to do with whether it runs on a real device or emulator. But in any case, your best bet is to follow up in an Android Studio bug.

**Comment by manumathew17** [comment]
Thanks, @jpd236  for the update
