### ISSUE TITLE
App Crashed on Android version 4.3 java.lang.NoClassDefFoundError: com.android.volley.toolbox.Volley

### ISSUE THREAD

**Issue by MuhammadHamzaSaleem** [google/volley#458]
java.lang.NoClassDefFoundError: com.android.volley.toolbox.Volley
                                                                                                    	at com.PITB.VentilatorStatus.CustomLibraries.MyVolley.init(MyVolley.java:44)
                                                                                                    	at com.PITB.VentilatorStatus.Utils.ApplicationState.init(ApplicationState.java:33)
                                                                                                    	at com.PITB.VentilatorStatus.Utils.ApplicationState.onCreate(ApplicationState.java:12)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:148)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:137)

**Comment by jpd236** [comment]
This isn't enough information for us to understand the problem. This class failing to load means that either your application has an issue with its build that causes that class to be excluded, or else there was an issue loading the class at runtime, which is unlikely to be an issue with Volley specifically since no other reports of this failure have arisen, but could be an issue with the device you're testing on.

If you'd like us to look more closely, please provide as much as possible of the following:

- A small sample app (source code) reproducing the issue
- More details about where you reproduced it - emulator or physical device? Which kind?
- Logcat output capturing any classloader failures, if any. I'd recommend starting adb logcat, force stopping the app, and then reproducing the problem. If there's an issue with the class loading, it should be captured prior to the NoClassDefFoundError.
