### ISSUE TITLE
NetworkDispatcher.run: Unhandled exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by mikewalkerjr** [google/volley#95]
I have been using Volley for a while now, but just updated the library today and starting running into some issues. My REST calls were failing with the error 

    [285580] NetworkDispatcher.run: Unhandled exception java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference                                              
        at java.lang.String$CaseInsensitiveComparator.compare(String.java:1104)                                                              
        at java.lang.String$CaseInsensitiveComparator.compare(String.java:1103)
        at java.util.TreeMap.put(TreeMap.java:554)
        at com.android.volley.NetworkResponse.toHeaderMap(NetworkResponse.java:145)
        at com.android.volley.NetworkResponse.<init>(NetworkResponse.java:0)
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:169)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:113)

From my searching I found it was issues with the headers. I did look at my headers and I could not find issues with them. I started searching more and lead me to `NetworkResponse.java` file in the Volley library. In the function `toHeaderMap`, there is a header with a null name:

    Header[name=null,value=HTTP/1.1 201 Created]

Which does follow the standard request header

    HTTP/1.1 200 OK
    Cache-Control: private
    Content-Type: text/plain; charset=utf-8
    Content-Encoding: gzip
    Vary: Accept-Encoding 
    Server: Microsoft-IIS/8.5
    X-AspNet-Version: 4.0.30319
    X-Powered-By: ASP.NET
    Date: Wed, 20 Sep 2017 16:11:06 GMT
    Connection: close
    Content-Length: 522

So the crash is occurring in the line

    headers.put(header.getName(), header.getValue());

Since the `header.getName()` is null, then the `headers.put` throws the `NullPointerException`. I changed the line to

    headers.put(header.getName() != null ? header.getName() : "", header.getValue());

And that crash didn't occur anymore. There were 2 other places I made the same update before my app works properly again. `DiskBasedCache.java` within the function `writeHeaderList` and `BasicNetwork.java` within the function `combineHeaders`.

I'm hoping this is the correct update for this issue.

**Comment by joebowbeer** [comment]
Good catch. I think this bug was introduced when a null check was removed from HurlStack:

https://github.com/google/volley/commit/b33a53f1793b475842f91a0fe166749118afcfc0#diff-7b52a41e4e3e2e1401e6486bee665d19L123

A unit test should be added to guard against this.

**Comment by jpd236** [comment]
Thanks @mikewalkerjr for the report, and thanks @joebowbeer for the find!

Agreed with the proposed fix. I was a little concerned that we more generally supported null header keys prior to my change, but it definitely would have crashed elsewhere (like DiskBasedCache), so we can be reasonably confident that there aren't HttpStacks in the wild that are doing this.

**Comment by goghAta** [comment]
Please release 1.0.1 version of volley as soon as possible. Or please fix/close this issue first so volley's snapshot will be more or less stable in that case. Thanks in advance.

**Comment by lovetcx** [comment]
thank you @mikewalkerjr  the same exception
